spring:
  security:
    oauth2:
      client:
        registration:
          github.client:  
          github.client-secret: 
        provider:
          keycloak:
            authorization-uri: 
            token-uri: 